### ISSUE TITLE
Add validation for Corporate Entity (PJ) names allowing numbers

### ISSUE THREAD

**Issue by duspada** [platformbuilders/validations#203]
**Description:**

Add a implementation of a new validation for Corporate Entity (PJ) names.

**Context:**

* Currently, the name validation focuses on Individual (PF) names, which do not allow numbers.
* However, company names (PJ) can contain numbers and certain special characters.

**Validation Requirements:**

* **Allow:**
  - Letters (uppercase and lowercase)
  - Numbers
  - Spaces
  - Common special characters in business names (e.g., ., &, /, -, ME, LTD, Inc.)
* **Disallow:**
  - Unconventional special characters
  - Invalid sequences that do not represent a company name

**Examples of Valid PJ Names:**

* **"123 Services LTD"**
* **"ABC Trading 456 Inc."**
* **"Company X&Y Solutions LLC"**
* **"Innovation and Technology 2023"**

**Possible Implementation:**

* Create a new validation function specifically for PJ names.
* Use regular expressions that include the allowed characters.
* Add unit tests to cover the new use cases.

**Notes:**

If you need support with implementation or testing, I am available to collaborate.

**Comment by guifl2001** [comment]
Working on this feature!
